# Generated by Django 6.0 on 2025-12-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('todo_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
