# Generated by Django 6.0 on 2025-12-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_todo_todo_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_indivi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
